name: Deploy Python functions to AWS Lambda

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  deploy1:
    if: github.event_name == 'push' || github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_1 }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_1 }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN_1 }}
          aws-region: us-east-1

      - name: Deploy Lambdas (Account 1)
        run: |
          for fn in add_inventory_item delete_inventory_item get_all_inventory_items get_inventory_item get_location_inventory_items
          do
            cd lambda/$fn
            zip function.zip lambda_function.py
            aws lambda update-function-code --function-name $fn --zip-file fileb://function.zip --publish
            rm function.zip
            cd ../../
          done

  deploy2:
    if: github.event_name == 'push' || github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_2 }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_2 }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN_2 }}
          aws-region: us-east-1

      - name: Deploy Lambdas (Account 2)
        run: |
          for fn in add_inventory_item delete_inventory_item get_all_inventory_items get_inventory_item get_location_inventory_items
          do
            cd lambda/$fn
            zip function.zip lambda_function.py
            aws lambda update-function-code --function-name $fn --zip-file fileb://function.zip --publish
            rm function.zip
            cd ../../
          done
